require("arche.plugins.undotree")
require("arche.plugins.treesitter")
require("arche.plugins.lazygit")
require("arche.plugins.telescope")
require("arche.plugins.lsp")
require("arche.plugins.lualine")
require("arche.plugins.blamer")
